-- Correção Completa do Schema SQLite
-- Resolve todos os problemas de PRIMARY KEY e estrutura

-- 1. Limpar tabelas problemáticas
DROP TABLE IF EXISTS TABELA_SALA_INVENTARIO;
DROP TABLE IF EXISTS SALA;

-- 2. Recriar SALA com estrutura correta
CREATE TABLE IF NOT EXISTS SALA (
    ID_SALA INTEGER PRIMARY KEY,
    NUMERO_SALA TEXT NOT NULL,
    NOME_SALA TEXT,
    ANDAR TEXT,
    BLOCO TEXT,
    CAPACIDADE INTEGER,
    TIPO_SALA TEXT,
    ATIVA BOOLEAN DEFAULT TRUE,
    DATA_CADASTRO DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- 3. Recriar TABELA_SALA_INVENTARIO com chave composta
CREATE TABLE IF NOT EXISTS TABELA_SALA_INVENTARIO (
    ID_SALA INTEGER NOT NULL,
    ID_INVENTARIO INTEGER NOT NULL,
    NUMERO_SALA TEXT NOT NULL,
    NOME_SALA TEXT,
    ANDAR TEXT,
    BLOCO TEXT,
    CAPACIDADE INTEGER,
    TIPO_SALA TEXT,
    ATIVA BOOLEAN DEFAULT TRUE,
    DATA_CADASTRO DATETIME DEFAULT CURRENT_TIMESTAMP,
    STATUS_COLETA TEXT DEFAULT 'PENDENTE',
    COLETA_FINALIZADA BOOLEAN DEFAULT FALSE,
    TOTAL_ITENS_COLETADOS INTEGER DEFAULT 0,
    PERCENTUAL_CONCLUSAO DECIMAL(5,2) DEFAULT 0,
    ID_PARTICIPANTE INTEGER,
    DATA_INICIO_COLETA DATETIME,
    DATA_FINALIZACAO_COLETA DATETIME,
    OBSERVACOES_FINALIZACAO TEXT,
    TOTAL_ITENS_SEM_ETIQUETA INTEGER DEFAULT 0,
    PRIMARY KEY (ID_SALA, ID_INVENTARIO)
);

-- 4. Verificar estrutura das tabelas principais
SELECT 'Estrutura de local_sala:' as info;
PRAGMA table_info(local_sala);

SELECT 'Estrutura de SALA:' as info;
PRAGMA table_info(SALA);

SELECT 'Estrutura de TABELA_SALA_INVENTARIO:' as info;
PRAGMA table_info(TABELA_SALA_INVENTARIO);

-- 5. Verificar chave primária de TABELA_SALA_INVENTARIO
SELECT 'Chave primária de TABELA_SALA_INVENTARIO:' as info;
SELECT sql FROM sqlite_master WHERE name='TABELA_SALA_INVENTARIO';

-- 6. Contar registros
SELECT 'Total de salas em local_sala:' as info, COUNT(*) as total FROM local_sala;
SELECT 'Total de salas em SALA:' as info, COUNT(*) as total FROM SALA;
SELECT 'Total de salas em TABELA_SALA_INVENTARIO:' as info, COUNT(*) as total FROM TABELA_SALA_INVENTARIO;

-- 7. Verificar coletas
SELECT 'Total de coletas:' as info, COUNT(*) as total FROM local_coleta;
SELECT 'Coletas com estado:' as info, COUNT(*) as total FROM local_coleta WHERE estado_encontrado IS NOT NULL;

VACUUM;
