-- Corrigir estrutura da TABELA_SALA_INVENTARIO
-- Problema: ID_SALA é PRIMARY KEY, mas deveria ser chave composta (ID_SALA + ID_INVENTARIO)

-- 1. Fazer backup dos dados
CREATE TABLE IF NOT EXISTS TABELA_SALA_INVENTARIO_BACKUP AS 
SELECT * FROM TABELA_SALA_INVENTARIO;

-- 2. Dropar tabela antiga
DROP TABLE IF EXISTS TABELA_SALA_INVENTARIO;

-- 3. Recriar com chave primária composta correta
CREATE TABLE TABELA_SALA_INVENTARIO (
    ID_SALA INTEGER NOT NULL,
    ID_INVENTARIO INTEGER NOT NULL,
    NUMERO_SALA TEXT NOT NULL,
    NOME_SALA TEXT,
    ANDAR TEXT,
    BLOCO TEXT,
    CAPACIDADE INTEGER,
    TIPO_SALA TEXT,
    ATIVA BOOLEAN DEFAULT TRUE,
    DATA_CADASTRO DATETIME DEFAULT CURRENT_TIMESTAMP,
    STATUS_COLETA TEXT DEFAULT 'PENDENTE',
    COLETA_FINALIZADA BOOLEAN DEFAULT FALSE,
    TOTAL_ITENS_COLETADOS INTEGER DEFAULT 0,
    PERCENTUAL_CONCLUSAO DECIMAL(5,2) DEFAULT 0,
    ID_PARTICIPANTE INTEGER,
    DATA_INICIO_COLETA DATETIME,
    DATA_FINALIZACAO_COLETA DATETIME,
    OBSERVACOES_FINALIZACAO TEXT,
    TOTAL_ITENS_SEM_ETIQUETA INTEGER DEFAULT 0,
    PRIMARY KEY (ID_SALA, ID_INVENTARIO)  -- CHAVE COMPOSTA CORRETA
);

-- 4. Restaurar dados (assumindo ID_INVENTARIO = 2 para dados existentes)
INSERT INTO TABELA_SALA_INVENTARIO 
SELECT 
    ID_SALA,
    COALESCE(ID_INVENTARIO, 2) as ID_INVENTARIO,  -- Usar inventário ativo
    NUMERO_SALA,
    NOME_SALA,
    ANDAR,
    BLOCO,
    CAPACIDADE,
    TIPO_SALA,
    ATIVA,
    DATA_CADASTRO,
    STATUS_COLETA,
    COLETA_FINALIZADA,
    TOTAL_ITENS_COLETADOS,
    PERCENTUAL_CONCLUSAO,
    ID_PARTICIPANTE,
    DATA_INICIO_COLETA,
    DATA_FINALIZACAO_COLETA,
    OBSERVACOES_FINALIZACAO,
    TOTAL_ITENS_SEM_ETIQUETA
FROM TABELA_SALA_INVENTARIO_BACKUP;

-- 5. Verificar resultado
SELECT 'Total de salas restauradas:' as info, COUNT(*) as total FROM TABELA_SALA_INVENTARIO;

-- 6. Limpar backup (opcional)
-- DROP TABLE TABELA_SALA_INVENTARIO_BACKUP;
