-- Verificar coletas com localizacao_encontrada
SELECT 
    c.ID,
    c.ID_PATRIMONIO,
    p.NUMERO as NUMERO_PATRIMONIO,
    p.DESCRICAO as DESCRICAO_PATRIMONIO,
    c.LOCALIZACAO_ENCONTRADA,
    c.LOCALIZACAO_ATUAL,
    s.NOME as NOME_SALA,
    c.DATA_COLETA,
    u.NOME_COMPLETO as COLETOR
FROM TABELA_COLETA c
LEFT JOIN TABELA_PATRIMONIO p ON c.ID_PATRIMONIO = p.ID
LEFT JOIN TABELA_SALA s ON p.ID_SALA = s.ID
LEFT JOIN TABELA_USUARIO u ON c.ID_COLETOR = u.ID
ORDER BY c.DATA_COLETA DESC
LIMIT 10;
