-- =====================================================
-- SCRIPT PARA CRIAR TABELA DE USUÁRIOS
-- Sistema de Inventário IFMT
-- =====================================================

-- Criar tabela de usuários
CREATE TABLE IF NOT EXISTS TABELA_USUARIO (
    ID SERIAL PRIMARY KEY,
    LOGIN VARCHAR(50) NOT NULL UNIQUE,
    SENHA_HASH VARCHAR(255) NOT NULL,
    NOME_COMPLETO VARCHAR(150) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    MATRICULA VARCHAR(20) UNIQUE,
    PERFIL VARCHAR(20) NOT NULL CHECK (PERFIL IN ('ADMIN', 'SUPERVISOR', 'COLETOR', 'CONSULTA')),
    ID_SETOR INTEGER,
    ATIVO CHAR(1) DEFAULT 'S' CHECK (ATIVO IN ('S', 'N')),
    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DATA_ULTIMO_ACESSO TIMESTAMP,
    TENTATIVAS_LOGIN INTEGER DEFAULT 0,
    BLOQUEADO CHAR(1) DEFAULT 'N' CHECK (BLOQUEADO IN ('S', 'N')),
    DATA_BLOQUEIO TIMESTAMP,
    DATA_EXPIRACAO_SENHA TIMESTAMP DEFAULT (CURRENT_TIMESTAMP + INTERVAL '90 days'),
    PRIMEIRO_ACESSO CHAR(1) DEFAULT 'S' CHECK (PRIMEIRO_ACESSO IN ('S', 'N')),
    OBSERVACOES TEXT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Criar índices para performance
CREATE INDEX IF NOT EXISTS idx_usuario_login ON TABELA_USUARIO(LOGIN);
CREATE INDEX IF NOT EXISTS idx_usuario_email ON TABELA_USUARIO(EMAIL);
CREATE INDEX IF NOT EXISTS idx_usuario_perfil ON TABELA_USUARIO(PERFIL);
CREATE INDEX IF NOT EXISTS idx_usuario_ativo ON TABELA_USUARIO(ATIVO);

-- Função para atualizar timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Trigger para atualizar updated_at automaticamente
CREATE TRIGGER update_usuario_updated_at 
    BEFORE UPDATE ON TABELA_USUARIO 
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Inserir usuário administrador padrão
-- Senha: admin123 (hash bcrypt)
INSERT INTO TABELA_USUARIO (LOGIN, SENHA_HASH, NOME_COMPLETO, EMAIL, PERFIL, PRIMEIRO_ACESSO) 
VALUES (
    'admin', 
    '$2a$10$N9qo8uLOickgx2ZMRZoMye1VdLIqCRFpb6AQBaOLLqI.xjVgLOjHi', 
    'Administrador do Sistema', 
    'admin@sistema.com', 
    'ADMIN', 
    'S'
)
ON CONFLICT (LOGIN) DO NOTHING;

-- Comentários na tabela
COMMENT ON TABLE TABELA_USUARIO IS 'Tabela de usuários do sistema';
COMMENT ON COLUMN TABELA_USUARIO.LOGIN IS 'Login único do usuário';
COMMENT ON COLUMN TABELA_USUARIO.SENHA_HASH IS 'Hash da senha (bcrypt)';
COMMENT ON COLUMN TABELA_USUARIO.PERFIL IS 'Perfil de acesso: ADMIN, SUPERVISOR, COLETOR, CONSULTA';
COMMENT ON COLUMN TABELA_USUARIO.ATIVO IS 'Status do usuário: S=Sim, N=Não';
COMMENT ON COLUMN TABELA_USUARIO.BLOQUEADO IS 'Usuário bloqueado: S=Sim, N=Não';
COMMENT ON COLUMN TABELA_USUARIO.PRIMEIRO_ACESSO IS 'Primeiro acesso: S=Sim, N=Não';

-- Verificar se a tabela foi criada com sucesso
SELECT 'Tabela TABELA_USUARIO criada com sucesso!' as resultado;

-- Verificar usuário administrador
SELECT 
    LOGIN, 
    NOME_COMPLETO, 
    EMAIL, 
    PERFIL, 
    ATIVO,
    DATA_CRIACAO
FROM TABELA_USUARIO 
WHERE LOGIN = 'admin';