-- Script para criação da TABELA_PATRIMONIO
-- Sistema de Inventário IFMT

CREATE TABLE IF NOT EXISTS TABELA_PATRIMONIO (
    ID SERIAL PRIMARY KEY,
    NUMERO VARCHAR(50) UNIQUE NOT NULL,
    STATUS VARCHAR(50) DEFAULT 'ATIVO',
    DESCRICAO TEXT,
    ROTULOS VARCHAR(500),
    ID_RESPONSAVEL INTEGER,
    VALOR_AQUISICAO DECIMAL(15,2),
    VALOR_DEPRECIADO DECIMAL(15,2),
    NUMERO_NOTA_FISCAL VARCHAR(100),
    NUMERO_SERIE VARCHAR(100),
    DATA_ENTRADA DATE,
    DATA_CARGA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FORNECEDOR VARCHAR(255),
    ID_SALA INTEGER,
    ESTADO_CONSERVACAO VARCHAR(50),
    FOREIGN KEY (ID_RESPONSAVEL) REFERENCES TABELA_RESPONSAVEL(ID),
    FOREIGN KEY (ID_SALA) REFERENCES TABELA_SALA(ID_SALA)
);

-- Índices para melhorar performance
CREATE INDEX IF NOT EXISTS idx_patrimonio_numero ON TABELA_PATRIMONIO(NUMERO);
CREATE INDEX IF NOT EXISTS idx_patrimonio_responsavel ON TABELA_PATRIMONIO(ID_RESPONSAVEL);
CREATE INDEX IF NOT EXISTS idx_patrimonio_sala ON TABELA_PATRIMONIO(ID_SALA);
CREATE INDEX IF NOT EXISTS idx_patrimonio_status ON TABELA_PATRIMONIO(STATUS);

-- Comentários
COMMENT ON TABLE TABELA_PATRIMONIO IS 'Tabela principal de patrimônios da instituição';
COMMENT ON COLUMN TABELA_PATRIMONIO.NUMERO IS 'Número único do patrimônio';
COMMENT ON COLUMN TABELA_PATRIMONIO.STATUS IS 'Status do patrimônio (ATIVO, INATIVO, BAIXADO)';
COMMENT ON COLUMN TABELA_PATRIMONIO.DESCRICAO IS 'Descrição detalhada do patrimônio';
COMMENT ON COLUMN TABELA_PATRIMONIO.ROTULOS IS 'Rótulos/tags para categorização';
COMMENT ON COLUMN TABELA_PATRIMONIO.VALOR_AQUISICAO IS 'Valor de aquisição do patrimônio';
COMMENT ON COLUMN TABELA_PATRIMONIO.VALOR_DEPRECIADO IS 'Valor atual depreciado';
COMMENT ON COLUMN TABELA_PATRIMONIO.ESTADO_CONSERVACAO IS 'Estado de conservação (NOVO, BOM, REGULAR, RUIM)';

PRINT 'Tabela PATRIMONIO criada com sucesso!';