-- Script para criação da TABELA_COLETA
-- Sistema de Inventário IFMT

CREATE TABLE IF NOT EXISTS TABELA_COLETA (
    ID SERIAL PRIMARY KEY,
    ID_INVENTARIO INTEGER NOT NULL,
    ID_PATRIMONIO INTEGER NOT NULL,
    ID_COLETOR INTEGER NOT NULL,
    DATA_COLETA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    STATUS_COLETA VARCHAR(50) DEFAULT 'COLETADO',
    OBSERVACAO_COLETA TEXT,
    LOCALIZACAO_ATUAL VARCHAR(255),
    LOCALIZACAO_ENCONTRADA VARCHAR(255),
    ESTADO_ENCONTRADO VARCHAR(50),
    DIVERGENCIA BOOLEAN DEFAULT FALSE,
    MOTIVO_DIVERGENCIA TEXT,
    LATITUDE DECIMAL(10,8),
    LONGITUDE DECIMAL(11,8),
    FOTO_PATRIMONIO TEXT,
    FOREIGN KEY (ID_INVENTARIO) REFERENCES TABELA_INVENTARIO(ID),
    FOREIGN KEY (ID_PATRIMONIO) REFERENCES TABELA_PATRIMONIO(ID),
    FOREIGN KEY (ID_COLETOR) REFERENCES TABELA_COLETOR(ID)
);

-- Índices para melhorar performance
CREATE INDEX IF NOT EXISTS idx_coleta_inventario ON TABELA_COLETA(ID_INVENTARIO);
CREATE INDEX IF NOT EXISTS idx_coleta_patrimonio ON TABELA_COLETA(ID_PATRIMONIO);
CREATE INDEX IF NOT EXISTS idx_coleta_coletor ON TABELA_COLETA(ID_COLETOR);
CREATE INDEX IF NOT EXISTS idx_coleta_data ON TABELA_COLETA(DATA_COLETA);
CREATE INDEX IF NOT EXISTS idx_coleta_status ON TABELA_COLETA(STATUS_COLETA);
CREATE INDEX IF NOT EXISTS idx_coleta_divergencia ON TABELA_COLETA(DIVERGENCIA);

-- Comentários
COMMENT ON TABLE TABELA_COLETA IS 'Tabela de coletas realizadas durante o inventário';
COMMENT ON COLUMN TABELA_COLETA.ID_INVENTARIO IS 'Referência ao inventário';
COMMENT ON COLUMN TABELA_COLETA.ID_PATRIMONIO IS 'Referência ao patrimônio coletado';
COMMENT ON COLUMN TABELA_COLETA.ID_COLETOR IS 'Referência ao coletor responsável pela coleta';
COMMENT ON COLUMN TABELA_COLETA.DATA_COLETA IS 'Data e hora da coleta';
COMMENT ON COLUMN TABELA_COLETA.STATUS_COLETA IS 'Status da coleta (COLETADO, NAO_ENCONTRADO, DANIFICADO)';
COMMENT ON COLUMN TABELA_COLETA.OBSERVACAO_COLETA IS 'Observações sobre a coleta';
COMMENT ON COLUMN TABELA_COLETA.LOCALIZACAO_ATUAL IS 'Localização cadastrada do patrimônio';
COMMENT ON COLUMN TABELA_COLETA.LOCALIZACAO_ENCONTRADA IS 'Localização onde foi encontrado';
COMMENT ON COLUMN TABELA_COLETA.ESTADO_ENCONTRADO IS 'Estado de conservação encontrado';
COMMENT ON COLUMN TABELA_COLETA.DIVERGENCIA IS 'Indica se há divergência entre o cadastrado e encontrado';
COMMENT ON COLUMN TABELA_COLETA.LATITUDE IS 'Coordenada de latitude da coleta';
COMMENT ON COLUMN TABELA_COLETA.LONGITUDE IS 'Coordenada de longitude da coleta';
COMMENT ON COLUMN TABELA_COLETA.FOTO_PATRIMONIO IS 'Caminho/URL da foto do patrimônio';

PRINT 'Tabela COLETA criada com sucesso!';