-- Script simplificado para criação da TABELA_PARTICIPANTE_INVENTARIO
-- Versão sem funções PL/pgSQL complexas

-- Criação da tabela principal
CREATE TABLE IF NOT EXISTS TABELA_PARTICIPANTE_INVENTARIO (
    ID_PARTICIPANTE SERIAL PRIMARY KEY,
    ID_INVENTARIO INTEGER NOT NULL,
    ID_USUARIO INTEGER NOT NULL,
    PAPEL VARCHAR(20) NOT NULL CHECK (PAPEL IN ('COORDENADOR', 'COLETOR', 'OBSERVADOR')),
    DATA_INCLUSAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DATA_REMOCAO TIMESTAMP NULL,
    ATIVO BOOLEAN DEFAULT TRUE,
    OBSERVACOES TEXT,
    DATA_ULTIMA_ATUALIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    -- Chaves estrangeiras
    CONSTRAINT FK_PARTICIPANTE_INVENTARIO 
        FOREIGN KEY (ID_INVENTARIO) 
        REFERENCES TABELA_INVENTARIO(ID_INVENTARIO) 
        ON DELETE CASCADE,
    
    CONSTRAINT FK_PARTICIPANTE_USUARIO 
        FOREIGN KEY (ID_USUARIO) 
        REFERENCES TABELA_USUARIO(ID_USUARIO) 
        ON DELETE CASCADE,
    
    -- Constraint única para evitar duplicatas
    CONSTRAINT UK_PARTICIPANTE_INVENTARIO_USUARIO 
        UNIQUE (ID_INVENTARIO, ID_USUARIO)
);

-- Índices para performance
CREATE INDEX IF NOT EXISTS IDX_PARTICIPANTE_INVENTARIO 
    ON TABELA_PARTICIPANTE_INVENTARIO(ID_INVENTARIO);

CREATE INDEX IF NOT EXISTS IDX_PARTICIPANTE_USUARIO 
    ON TABELA_PARTICIPANTE_INVENTARIO(ID_USUARIO);

CREATE INDEX IF NOT EXISTS IDX_PARTICIPANTE_PAPEL 
    ON TABELA_PARTICIPANTE_INVENTARIO(PAPEL);

CREATE INDEX IF NOT EXISTS IDX_PARTICIPANTE_ATIVO 
    ON TABELA_PARTICIPANTE_INVENTARIO(ATIVO);

-- View para facilitar consultas
CREATE OR REPLACE VIEW VW_PARTICIPANTES_INVENTARIO AS
SELECT 
    p.ID_PARTICIPANTE,
    p.ID_INVENTARIO,
    i.NOME AS NOME_INVENTARIO,
    i.ANO AS ANO_INVENTARIO,
    p.ID_USUARIO,
    u.NOME AS NOME_USUARIO,
    u.EMAIL AS EMAIL_USUARIO,
    u.PERFIL AS PERFIL_USUARIO,
    p.PAPEL,
    p.DATA_INCLUSAO,
    p.DATA_REMOCAO,
    p.ATIVO,
    p.OBSERVACOES,
    p.DATA_ULTIMA_ATUALIZACAO
FROM TABELA_PARTICIPANTE_INVENTARIO p
INNER JOIN TABELA_INVENTARIO i ON p.ID_INVENTARIO = i.ID_INVENTARIO
INNER JOIN TABELA_USUARIO u ON p.ID_USUARIO = u.ID_USUARIO;

-- Inserir dados de teste (opcional)
INSERT INTO TABELA_PARTICIPANTE_INVENTARIO (ID_INVENTARIO, ID_USUARIO, PAPEL, OBSERVACOES)
SELECT 1, 1, 'COORDENADOR', 'Coordenador principal do inventário'
WHERE EXISTS (SELECT 1 FROM TABELA_INVENTARIO WHERE ID_INVENTARIO = 1)
  AND EXISTS (SELECT 1 FROM TABELA_USUARIO WHERE ID_USUARIO = 1)
  AND NOT EXISTS (SELECT 1 FROM TABELA_PARTICIPANTE_INVENTARIO WHERE ID_INVENTARIO = 1 AND ID_USUARIO = 1);

SELECT 'Tabela TABELA_PARTICIPANTE_INVENTARIO criada com sucesso!' as resultado;