-- Script para criação da TABELA_INVENTARIO
-- Sistema de Inventário IFMT

CREATE TABLE IF NOT EXISTS TABELA_INVENTARIO (
    ID SERIAL PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    ANO INTEGER NOT NULL,
    DATA_INICIO DATE NOT NULL,
    DATA_FIM DATE,
    OBSERVACAO TEXT,
    STATUS_INVENTARIO VARCHAR(50) DEFAULT 'PLANEJADO',
    RESPONSAVEL_INVENTARIO VARCHAR(255),
    TOTAL_PATRIMONIOS INTEGER DEFAULT 0,
    PATRIMONIOS_COLETADOS INTEGER DEFAULT 0,
    PERCENTUAL_CONCLUSAO DECIMAL(5,2) DEFAULT 0.00,
    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DATA_ULTIMA_ATUALIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Índices
CREATE INDEX IF NOT EXISTS idx_inventario_ano ON TABELA_INVENTARIO(ANO);
CREATE INDEX IF NOT EXISTS idx_inventario_status ON TABELA_INVENTARIO(STATUS_INVENTARIO);
CREATE INDEX IF NOT EXISTS idx_inventario_data_inicio ON TABELA_INVENTARIO(DATA_INICIO);
CREATE INDEX IF NOT EXISTS idx_inventario_data_fim ON TABELA_INVENTARIO(DATA_FIM);

-- Comentários
COMMENT ON TABLE TABELA_INVENTARIO IS 'Tabela de inventários realizados na instituição';
COMMENT ON COLUMN TABELA_INVENTARIO.NOME IS 'Nome/título do inventário';
COMMENT ON COLUMN TABELA_INVENTARIO.ANO IS 'Ano de referência do inventário';
COMMENT ON COLUMN TABELA_INVENTARIO.DATA_INICIO IS 'Data de início do inventário';
COMMENT ON COLUMN TABELA_INVENTARIO.DATA_FIM IS 'Data de conclusão do inventário';
COMMENT ON COLUMN TABELA_INVENTARIO.OBSERVACAO IS 'Observações gerais sobre o inventário';
COMMENT ON COLUMN TABELA_INVENTARIO.STATUS_INVENTARIO IS 'Status do inventário (PLANEJADO, EM_ANDAMENTO, CONCLUIDO, CANCELADO)';
COMMENT ON COLUMN TABELA_INVENTARIO.RESPONSAVEL_INVENTARIO IS 'Responsável geral pelo inventário';
COMMENT ON COLUMN TABELA_INVENTARIO.TOTAL_PATRIMONIOS IS 'Total de patrimônios a serem inventariados';
COMMENT ON COLUMN TABELA_INVENTARIO.PATRIMONIOS_COLETADOS IS 'Quantidade de patrimônios já coletados';
COMMENT ON COLUMN TABELA_INVENTARIO.PERCENTUAL_CONCLUSAO IS 'Percentual de conclusão do inventário';

-- Trigger para atualizar data de última atualização
CREATE OR REPLACE FUNCTION update_inventario_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.DATA_ULTIMA_ATUALIZACAO = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_inventario_timestamp
    BEFORE UPDATE ON TABELA_INVENTARIO
    FOR EACH ROW
    EXECUTE FUNCTION update_inventario_timestamp();

-- Inserção de dados de exemplo
INSERT INTO TABELA_INVENTARIO (NOME, ANO, DATA_INICIO, RESPONSAVEL_INVENTARIO, OBSERVACAO) VALUES 
('Inventário Anual 2024', 2024, '2024-01-15', 'ADMINISTRADOR GERAL', 'Inventário anual completo de todos os patrimônios'),
('Inventário Laboratórios 2024', 2024, '2024-06-01', 'RESPONSÁVEL LABORATÓRIOS', 'Inventário específico dos laboratórios de ensino')
ON CONFLICT DO NOTHING;

PRINT 'Tabela INVENTARIO criada com sucesso!';